services:
  - type: web
    name: EcoPowerSolution
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-cvolk9pr0fns739q0d5g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: ecopower
      - key: DB_USER
        value: ecopower_user
      - key: DB_PASS
        value: qpNdkE7IRVhpNT7QfjIlbFN6kyfLUVYk
      - key: SESSION_SECRET
        value: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
