services:
  - type: web
    name: EcoPowerSolution
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_NAME
        value: ecopower
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: finalpass
      - key: SESSION_SECRET
        value: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
